apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: ctbc-yaml
  labels:
    app: opensearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  selector:
    app: opensearch
