apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: ctbc-yaml
spec:
  serviceName: opensearch
  replicas: 3
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      imagePullSecrets:
        - name: dockerhub-wox080xow
      securityContext:
        fsGroup: 1000
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:3.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: bootstrap.memory_lock
          value: "true"
        - name: "OPENSEARCH_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
          subPathExpr: opensearch/data/$(NODE_NAME)
        - name: config
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
      volumes:
      - name: config
        configMap:
          name: opensearch-config
      - name: opensearch-data
        persistentVolumeClaim:
          claimName: opensearch-pvc
      initContainers:
      - name: increase-vm-max-map
        image: busybox:1.37.0
        imagePullPolicy: IfNotPresent
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
